// Map country/team names to ISO 3166-1 alpha-2 codes for standard country flags
// Used with https://flagcdn.com/w160/{code}.png

const NAME_TO_ISO: Record<string, string> = {
  // South America
  "argentina": "ar",
  "brazil": "br",
  "brasil": "br",
  "uruguay": "uy",
  "paraguay": "py",
  "chile": "cl",
  "colombia": "co",
  "ecuador": "ec",
  "peru": "pe",
  "bolivia": "bo",
  "venezuela": "ve",
  // North & Central America
  "united states": "us",
  "usa": "us",
  "us": "us",
  "mexico": "mx",
  "canada": "ca",
  "costa rica": "cr",
  "panama": "pa",
  "honduras": "hn",
  "jamaica": "jm",
  "el salvador": "sv",
  "guatemala": "gt",
  "haiti": "ht",
  "curacao": "cw",
  "curaçao": "cw",
  "trinidad and tobago": "tt",
  // Europe
  "england": "gb-eng",
  "scotland": "gb-sct",
  "wales": "gb-wls",
  "northern ireland": "gb-nir",
  "spain": "es",
  "france": "fr",
  "germany": "de",
  "italy": "it",
  "portugal": "pt",
  "netherlands": "nl",
  "holland": "nl",
  "belgium": "be",
  "switzerland": "ch",
  "austria": "at",
  "croatia": "hr",
  "serbia": "rs",
  "denmark": "dk",
  "sweden": "se",
  "norway": "no",
  "finland": "fi",
  "iceland": "is",
  "poland": "pl",
  "ukraine": "ua",
  "czech republic": "cz",
  "czechia": "cz",
  "slovakia": "sk",
  "slovenia": "si",
  "hungary": "hu",
  "romania": "ro",
  "bulgaria": "bg",
  "greece": "gr",
  "turkey": "tr",
  "türkiye": "tr",
  "ireland": "ie",
  "republic of ireland": "ie",
  "albania": "al",
  "north macedonia": "mk",
  "bosnia and herzegovina": "ba",
  "montenegro": "me",
  "kosovo": "xk",
  "russia": "ru",
  "georgia": "ge",
  "armenia": "am",
  "azerbaijan": "az",
  "belarus": "by",
  "moldova": "md",
  "estonia": "ee",
  "latvia": "lv",
  "lithuania": "lt",
  "luxembourg": "lu",
  "malta": "mt",
  "cyprus": "cy",
  // Africa
  "morocco": "ma",
  "algeria": "dz",
  "tunisia": "tn",
  "egypt": "eg",
  "libya": "ly",
  "senegal": "sn",
  "ivory coast": "ci",
  "côte d'ivoire": "ci",
  "cote d'ivoire": "ci",
  "ghana": "gh",
  "nigeria": "ng",
  "cameroon": "cm",
  "south africa": "za",
  "mali": "ml",
  "burkina faso": "bf",
  "guinea": "gn",
  "cape verde": "cv",
  "cabo verde": "cv",
  "dr congo": "cd",
  "congo dr": "cd",
  "democratic republic of congo": "cd",
  "republic of the congo": "cg",
  "kenya": "ke",
  "uganda": "ug",
  "tanzania": "tz",
  "ethiopia": "et",
  "angola": "ao",
  "mozambique": "mz",
  "zimbabwe": "zw",
  "zambia": "zm",
  "namibia": "na",
  "gabon": "ga",
  "togo": "tg",
  "benin": "bj",
  "sierra leone": "sl",
  "liberia": "lr",
  "madagascar": "mg",
  "mauritania": "mr",
  "sudan": "sd",
  "south sudan": "ss",
  "comoros": "km",
  "equatorial guinea": "gq",
  "guinea-bissau": "gw",
  "central african republic": "cf",
  "chad": "td",
  "niger": "ne",
  "rwanda": "rw",
  "burundi": "bi",
  "eritrea": "er",
  "djibouti": "dj",
  // Asia
  "japan": "jp",
  "south korea": "kr",
  "korea republic": "kr",
  "korea": "kr",
  "north korea": "kp",
  "korea dpr": "kp",
  "china": "cn",
  "china pr": "cn",
  "iran": "ir",
  "iraq": "iq",
  "saudi arabia": "sa",
  "qatar": "qa",
  "united arab emirates": "ae",
  "uae": "ae",
  "bahrain": "bh",
  "oman": "om",
  "kuwait": "kw",
  "jordan": "jo",
  "lebanon": "lb",
  "syria": "sy",
  "yemen": "ye",
  "palestine": "ps",
  "israel": "il",
  "australia": "au",
  "new zealand": "nz",
  "uzbekistan": "uz",
  "tajikistan": "tj",
  "turkmenistan": "tm",
  "kyrgyzstan": "kg",
  "kazakhstan": "kz",
  "afghanistan": "af",
  "pakistan": "pk",
  "india": "in",
  "bangladesh": "bd",
  "sri lanka": "lk",
  "nepal": "np",
  "bhutan": "bt",
  "maldives": "mv",
  "thailand": "th",
  "vietnam": "vn",
  "indonesia": "id",
  "malaysia": "my",
  "singapore": "sg",
  "philippines": "ph",
  "myanmar": "mm",
  "cambodia": "kh",
  "laos": "la",
  "brunei": "bn",
  "mongolia": "mn",
  "taiwan": "tw",
  "hong kong": "hk",
  // Spanish FIFA names (Mundial 2026)
  "alemania": "de",
  "arabia saudí": "sa",
  "arabia saudita": "sa",
  "argelia": "dz",
  "australia": "au",
  "austria": "at",
  "bélgica": "be",
  "belgica": "be",
  "bosnia y herzegovina": "ba",
  "canadá": "ca",
  "catar": "qa",
  "chequia": "cz",
  "costa de marfil": "ci",
  "croacia": "hr",
  "curazao": "cw",
  "ee. uu.": "us",
  "ee.uu.": "us",
  "egipto": "eg",
  "escocia": "gb-sct",
  "españa": "es",
  "espana": "es",
  "francia": "fr",
  "haití": "ht",
  "haiti": "ht",
  "inglaterra": "gb-eng",
  "irak": "iq",
  "islas de cabo verde": "cv",
  "japón": "jp",
  "japon": "jp",
  "jordania": "jo",
  "marruecos": "ma",
  "méxico": "mx",
  "mexico": "mx",
  "noruega": "no",
  "nueva zelanda": "nz",
  "panamá": "pa",
  "panama": "pa",
  "países bajos": "nl",
  "paises bajos": "nl",
  "paraguay": "py",
  "rd congo": "cd",
  "ri de irán": "ir",
  "ri de iran": "ir",
  "república de corea": "kr",
  "republica de corea": "kr",
  "senegal": "sn",
  "sudáfrica": "za",
  "sudafrica": "za",
  "suecia": "se",
  "suiza": "ch",
  "turquía": "tr",
  "turquia": "tr",
  "túnez": "tn",
  "tunez": "tn",
  "uruguay": "uy",
  "uzbekistán": "uz",
  "uzbekistan": "uz",
  "argentina": "ar",
  "brasil": "br",
  "colombia": "co",
  "ecuador": "ec",
  "ghana": "gh",
  "portugal": "pt",
};

export function getCountryFlagUrl(name: string | null | undefined): string | null {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  const iso = NAME_TO_ISO[key];
  if (!iso) return null;
  return `https://flagcdn.com/w160/${iso}.png`;
}
